server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: postgres
    password: "AhmadSajidSura2003"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

product-service:
  base-url: http://localhost:8082

logging:
  level:
    root: INFO
    org.springframework.web.client: DEBUG